POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "admi",
    "password": "12345"
}

###

@authorizationToken =

GET http://localhost:3000/api/users
Authorization: Bearer {{authorizationToken}}

###

POST http://localhost:3000/api/users
Authorization: Bearer {{authorizationToken}}
Content-Type: application/json

{
    "username": "Juan",
    "password": "12345",
    "displayName": "Juan Pérez",
    "email": "juan@gmail.com"
}

###

DELETE http://localhost:3000/users/Juan

###

PATCH http://localhost:3000/users/Juan
Content-Type: application/json

{
    "name": "Pedro"
}