POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "admi",
    "password": "1234"
}

###

@authorizationToken = e3af01a5bba3f0d2fb8a6deabaaf9b3ee2dec5931a1a585a924c5c0ed147f7e6
GET http://localhost:3000/api/users
Authorization: Bearer {{authorizationToken}}

###

POST http://localhost:3000/api/users
Authorization: Bearer {{authorizationToken}}
Content-Type: application/json

{
    "username": "Martina",
    "password": "200653",
    "displayName": "Martina Castro",
    "email": "martina@gmail.com",
    "role": "admin"
}

###

DELETE http://localhost:3000/api/users/Martina
Authorization: Bearer {{authorizationToken}}

###

PATCH http://localhost:3000/api/users/Juan
Authorization: Bearer {{authorizationToken}}
Content-Type: application/json

{
    "username": "Pedro"
}